name: Publish Package to npmjs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@Devilz1'
      - name: Replace token
          run: echo "$(sed 's/\(_authToken=\)[a-z0-9]*\($\)/\1${{ env.GITHUB_TOKEN }}\2/g' .npmrc)" > .npmrc
          env:
            GITHUB_TOKEN: ${{ secrets.NPM_KEY }}
      - name: Publish
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

