name: Publish package

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          token: ${{ secrets.NPM_KEY }}
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@microfront-poligon'

      - name: Replace token
        run: echo "$(sed 's/\(_authToken=\)[a-z0-9]*\($\)/\1${{ env.GITHUB_TOKEN }}\2/g' .npmrc)" > .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_KEY }}

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: master
          semantic_version: 17.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_KEY }}

      - name: Publish To GitHub Package
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_KEY}}
